#!/bin/sh

res()
{
    TTYS="/dev/ttyS0 /dev/ttyAMA0 /dev/ttyUSB0"
    THIS=`tty`
    for tty in $TTYS; do
	if [ "$THIS" = "$tty" ]; then
	    resize
	fi
    done
}

export LANG="en_US.UTF8"
export LC_ALL="en_US.UTF8"
export LC_CTYPE="en_US.UTF8"

# export TERM="vt220"
export PS1="`res`\u@\h:\w \$ "
export EDITOR=vi

alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias vim=vi
alias emacs=mg
