# Glue for cross compiling lipify <http://ipify.org>
PKGVER     := 0.2
PKG        := lipify-$(PKGVER)
PKGSUFFIX  := tar.xz
PKGPATCHES :=
PKGURL      = https://github.com/troglobit/$(PKGNAME)/releases/download/v$(PKGVER)/$(PKGTAR)

include $(ROOTDIR)/system/pkg.mk
