# Glue for cross compiling lipify <http://ipify.org>
PKGVER     := 0.2
PKG        := lipify-$(PKGVER)
PKGSUFFIX  := tar.xz
PKGPATCHES :=
PKGURL      = $(TROGLOHUB)/$(PKGNAME)/releases/download/v$(PKGVER)/$(PKGTAR)

include $(ROOTDIR)/pkg.mk
