#!/bin/sh
ifname="$1"
action="$2"

case "$action.$ifname" in
up.eth0)
	if [ -f /var/run/udhcpc.pid ]; then
	       kill `cat /var/run/udhcpc.pid`
	fi
	/sbin/udhcpc -i eth0 -p /var/run/udhcpc.pid
	;;
down.eth0)
	if [ -f /var/run/udhcpc.pid ]; then
	       kill `cat /var/run/udhcpc.pid`
	fi
	;;
esac
