#!/bin/sh -e

# POST upload format:
# -----------------------------29995809218093749221856446032^M
# Content-Disposition: form-data; name="file1"; filename="..."^M
# Content-Type: application/octet-stream^M
# ^M    <--------- headers end with empty line
# file contents
# file contents
# file contents
# ^M    <--------- extra empty line
# -----------------------------29995809218093749221856446032--^M

file=/tmp/$$-$RANDOM

trap atexit 0

atexit() {
	rm -rf $file
	if [ $pre ]; then
		printf "\n</pre>\n"
		pre=
	fi
	if [ ! $ok ]; then
		printf "<H1>FAILED!</H1>\r\nAn error occurred. See log above<"
	fi
	printf "</body></html>\n"
}

CR=`printf '\r'`

# CGI output must start with at least empty line (or headers)
printf "Content-type: text/html\r\n\r\n"

cat <<-EOH
	<html>
	<head>
	<title>Upgrade status</title>
	</head>
	<body>
	<h1>System upgrade</h1>
	<pre>
EOH
pre=1

exec 2>&1

IFS="$CR"
read -r delim_line
IFS=""

while read -r line; do
    test x"$line" = x"" && break
    test x"$line" = x"$CR" && break
done

mkdir $file
cd $file
tar zxf -
if [ -f runme.sh ]; then
	sh runme.sh
else
	for i in 0 1 2 3; do
		if [ -f mtd$i ]; then
			flashcp -v mtd$i /dev/mtd$i
		fi
	done
fi

printf "</pre>\r\n"
cat <<EOT
<h1>System upgraded</h1>
<p>The upgrade installed successfully. Please <a href="/cgi-bin/reboot-fpga">reboot</a> to activate.</p>
EOT

ok=1
