#!/bin/sh

mount -a
mount -o remount,rw /

# create some dirs to avoid warning messages
mkdir -p /var/run
mkdir -p /var/log
mkdir -p /var/lib
mkdir -p /etc/network/if-up.d
mkdir -p /etc/network/if-pre-up.d

# Logs to /var/log/messages
hostname -F /etc/hostname
syslogd

# make home directory for root user
mkdir -p /root

# telnetd requires this
mkdir -p /dev/pts && \
 mount -t devpts none /dev/pts &

# Start kernel logger now that syslogd likely is up
klogd

cat <<EOF >/etc/httpd.conf
H:/http
I:index.html
/cgi-bin:root:$passwd
EOF

# Bring up all /etc/network/interfaces
ifup -a 2>&1 >/dev/null

# Start SNMP daemon
mini_snmpd -c public -D "TroglOS Linux Virtual Devboard" \
        -L GitHub -C troglobit@gmail.com -i eth0 -v -t 10 1>/dev/null 2>&1 &

