#! /bin/sh

mount -a

mount -o remount,rw /

# create some dirs to avoid warning messages
mkdir -p /var/run
mkdir -p /etc/network/if-up.d
mkdir -p /etc/network/if-pre-up.d

# make home directory for root user
mkdir -p /root

# telnetd requires this
mkdir -p /dev/pts && \
 mount -t devpts none /dev/pts &

echo "Configuring loopback device"
ip addr add 127.0.0.1/8 dev lo
ip link set lo up

# Fixup root password
passwd="root"
echo "Root password is $passwd"
echo "root:`cryptpw "$passwd"`:0:0::/root:/bin/sh" >/etc/passwd

cat <<EOF >/etc/httpd.conf
H:/http
I:index.html
/cgi-bin:root:$passwd
EOF

modprobe g_serial

echo "Started!"
