#!/bin/sh

mount -a
mount -o remount,rw /

# create some dirs to avoid warning messages
mkdir -p /var/run
mkdir -p /var/log
mkdir -p /var/lib
mkdir -p /etc/network/if-up.d
mkdir -p /etc/network/if-pre-up.d

# Logs to /var/log/messages
hostname `cat /etc/hostname`
syslogd

# make home directory for root user
mkdir -p /root

# telnetd requires this
mkdir -p /dev/pts && \
 mount -t devpts none /dev/pts &

# Start kernel logger now that syslogd likely is up
klogd

# Setup loopback device, no networking without it
ip addr add 127.0.0.1/8 dev lo
ip link set lo up

cat <<EOF >/etc/httpd.conf
H:/http
I:index.html
/cgi-bin:root:$passwd
EOF

