#!/bin/sh

# Use /etc/mactab to rename interfaces before grouping
[ -f /etc/mactab ] && nameif -s

# Place all eth* interfaces in the "port" group, such that we can
# reference them together later, e.g. in /etc/network/interfaces.
awk -F: '
    /^\s*eth|^\s*lan|^\s*p/ {
        print("link set dev", $1, " group port");
    }' </proc/net/dev | ip -batch -

exit 0
